export const REGISTER_FAIL = 'REGISTER_FAIL';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const ADD_ITEM_SUCCESS = 'ADD_ITEM_SUCCESS';
export const ADD_ITEM_FAIL = 'ADD_ITEM_FAIL';
export const GET_ITEMS_SUCCESS = 'GET_ITEMS_SUCCESS';
export const GET_ITEMS_FAIL = 'GET_ITEMS_FAIL';
export const LOGOUT = 'LOGOUT';
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
export const SEND_MESSAGE_FAIL = 'SEND_MESSAGE_FAIL';

export const FETCH_MONTHLY_EXPENSE_FAIL = 'FETCH_MONTHLY_EXPENSE_FAIL';
export const FETCH_MONTHLY_EXPENSE_SUCCESS = 'FETCH_MONTHLY_EXPENSE_SUCCESS';
export const FETCH_WEEKLY_EXPENSE_FAIL = 'FETCH_WEEKLY_EXPENSE_FAIL';
export const FETCH_WEEKLY_EXPENSE_SUCCESS = 'FETCH_WEEKLY_EXPENSE_SUCCESS';
export const FETCH_YEARLY_EXPENSE_FAIL = 'FETCH_YEARLY_EXPENSE_FAIL';
export const FETCH_YEARLY_EXPENSE_SUCCESS = 'FETCH_YEARLY_EXPENSE_SUCCESS';


export const EDIT_PROFILE = 'EDIT_PROFILE';
export const DELETE_ACCOUNT = 'DELETE_ACCOUNT';
export const CLEAR_PROFILE = 'CLEAR_PROFILE';


export const LOGIN_REQUIRED = 'LOGIN_REQUIRED';
export const REQUEST_PASSWORD_RESET_SUCCESS = 'REQUEST_PASSWORD_RESET_SUCCESS';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const REQUEST_PASSWORD_RESET_FAIL = 'REQUEST_PASSWORD_FAIL';
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL';